### PR TITLE
Convert to go.mod

### PR DESCRIPTION
**Pull request by candlerb**
* Replace vendor directory with go.mod
* Fix to compile with current promlog
* Build with go 1.13

Supercedes PR #7

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you keep the vendoring please?

**Comment by candlerb** [comment]
Please can you explain exactly what you mean by "keep the vendoring"?

With `go.mod`, all the dependencies are explicitly linked to, and exact versions fetched on demand.  As far as I can see, `go.mod` *is* vendoring.

I don't know how you'd use go.mod whilst still keeping copies of third-party packages in a legacy vendor directory.  I suppose you could give all the packages new names like `github.com/RobustPerception/nrpe_exporter/prometheus/common/promlog` - it just doesn't seem right.

**Comment by brian-brazil** [comment]
Keeping the vendor directory. It's the standard for Prometheus stuff.

**Comment by candlerb** [comment]
I'm still not sure whether:

1. You don't want the `go.mod` mechanism used at all; or
2. You are happy to use `go.mod`, but still want the vendor directory (if so, why - to be able to build with go < 1.11 perhaps?)

I did find [this blog/FAQ](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away).  It appears it is possible to leave code in vendor, but it is ignored unless you do `go build -mod=vendor`.

That implies doing stuff with travis: make it test both `go build` and `go build -mod=vendor`, otherwise the vendor code will become stale.  I don't know how to make travis do that.

**Comment by brian-brazil** [comment]
2.

**Comment by candlerb** [comment]
Something weird is going on.

I am trying to migrate to go modules *without* changing the dependencies.  Following the instructions [here](https://blog.golang.org/migrating-to-go-modules) I do:

```
ubuntu@builder:~/nrpe_exporter$ ls -l go.*
ls: cannot access 'go.*': No such file or directory

ubuntu@builder:~/nrpe_exporter$ go mod init github.com/RobustPerception/nrpe_exporter
go: creating new go.mod: module github.com/RobustPerception/nrpe_exporter
go: copying requirements from vendor/vendor.json
go: converting vendor/vendor.json: stat github.com/go-kit/log@: unknown revision

ubuntu@builder:~/nrpe_exporter$ cat go.mod
module github.com/RobustPerception/nrpe_exporter

go 1.13

require (
	github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
	github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
	github.com/go-kit/kit v0.5.1-0.20170917202734-0d313fb5fb3a
	github.com/go-logfmt/logfmt v0.3.0
	github.com/go-stack/stack v1.6.0
	github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
	github.com/pkg/errors v0.8.1-0.20170910134614-2b3a18b5f0fb
	github.com/prometheus/common v0.0.0-20170908161822-2f17f4a9d485
	gopkg.in/alecthomas/kingpin.v2 v2.2.5
)
```

All good so far: notice the dependency on an old version of prometheus/common (which promlog comes from).

But then it breaks when I try to build:

```
ubuntu@builder:~/nrpe_exporter$ go build -mod=readonly ./...
go: updates to go.sum needed, disabled by -mod=readonly

ubuntu@builder:~/nrpe_exporter$ go build ./...
go: finding github.com/aperum/nrpe latest
# github.com/RobustPerception/nrpe_exporter
./nrpe_exporter.go:124:37: cannot use &allowedLevel (type *promlog.AllowedLevel) as type *promlog.Config in argument to flag.AddFlags
./nrpe_exporter.go:128:23: cannot use allowedLevel (type promlog.AllowedLevel) as type *promlog.Config in argument to promlog.New

ubuntu@builder:~/nrpe_exporter$ cat go.mod
module github.com/RobustPerception/nrpe_exporter

go 1.13

require (
	github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
	github.com/alecthomas/units v0.0.0-20190717042225-c3de453c63f4
	github.com/aperum/nrpe v0.0.0-20170524093721-53d9ca02dfca
	github.com/go-kit/kit v0.9.0
	github.com/go-logfmt/logfmt v0.4.0
	github.com/go-stack/stack v1.8.0
	github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
	github.com/pkg/errors v0.8.1
	github.com/prometheus/client_golang v1.2.1
	github.com/prometheus/common v0.7.0
	gopkg.in/alecthomas/kingpin.v2 v2.2.6
)
```

Notice how the dependencies have all been auto-updated, including prometheus/common v0.7.0 (which has a different logger argument).  Even "go list" does this.

Previously I had fixed this simply by changing nrpe_exporter to use the new API, and removed the outdated code from `vendor/`.

Now I want to add go.mod whilst keeping it in sync with the vendor directory, and I can't see how to do this.

This is with go1.13.4

**Comment by brian-brazil** [comment]
That's missing a go mod vendor.

**Comment by candlerb** [comment]
That still bumps the dependency to `github.com/prometheus/common v0.7.0`

```
ubuntu@builder:~/nrpe_exporter$ go mod init github.com/RobustPerception/nrpe_exporter
go: creating new go.mod: module github.com/RobustPerception/nrpe_exporter
go: copying requirements from vendor/vendor.json
go: converting vendor/vendor.json: stat github.com/go-kit/log@: unknown revision
ubuntu@builder:~/nrpe_exporter$ cat go.mod
module github.com/RobustPerception/nrpe_exporter

go 1.13

require (
	github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
	github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
	github.com/go-kit/kit v0.5.1-0.20170917202734-0d313fb5fb3a
	github.com/go-logfmt/logfmt v0.3.0
	github.com/go-stack/stack v1.6.0
	github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
	github.com/pkg/errors v0.8.1-0.20170910134614-2b3a18b5f0fb
	github.com/prometheus/common v0.0.0-20170908161822-2f17f4a9d485
	gopkg.in/alecthomas/kingpin.v2 v2.2.5
)
ubuntu@builder:~/nrpe_exporter$ go mod vendor
go: finding github.com/aperum/nrpe latest
ubuntu@builder:~/nrpe_exporter$ cat go.mod
module github.com/RobustPerception/nrpe_exporter

go 1.13

require (
	github.com/aperum/nrpe v0.0.0-20170524093721-53d9ca02dfca
	github.com/go-kit/kit v0.9.0
	github.com/prometheus/client_golang v1.2.1
	github.com/prometheus/common v0.7.0
	gopkg.in/alecthomas/kingpin.v2 v2.2.6
)
```

**Comment by brian-brazil** [comment]
Update the code if you need to, I don't particularly mind what versions we end up with.

**Comment by candlerb** [comment]
By inspecting the `vendor/` directory, I've discovered it is missing some dependencies:

* `github.com/aperum/nrpe`
* `github.com/prometheus/client_golang/prometheus`
* `github.com/prometheus/client_golang/prometheus/promhttp`
* `github.com/prometheus/common/version`

and hence `go build -mod=vendor` fails.  I did wonder at first whether all "prometheus" dependencies were intentionally left out, but `github.com/prometheus/common/promlog` and `github.com/prometheus/common/promlog/flag` *are* present.

If I revert to go 1.8, and try building in a fresh `~/go` tree, I see the same:

```
ubuntu@builder:~/go/src/github.com/RobustPerception/nrpe_exporter$ go build
nrpe_exporter.go:9:2: cannot find package "github.com/aperum/nrpe" in any of:
	/home/ubuntu/go/src/github.com/RobustPerception/nrpe_exporter/vendor/github.com/aperum/nrpe (vendor tree)
	/usr/local/go/src/github.com/aperum/nrpe (from $GOROOT)
	/home/ubuntu/go/src/github.com/aperum/nrpe (from $GOPATH)
nrpe_exporter.go:12:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/home/ubuntu/go/src/github.com/RobustPerception/nrpe_exporter/vendor/github.com/prometheus/client_golang/prometheus (vendor tree)
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/home/ubuntu/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
nrpe_exporter.go:13:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
	/home/ubuntu/go/src/github.com/RobustPerception/nrpe_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp (vendor tree)
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
	/home/ubuntu/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
nrpe_exporter.go:16:2: cannot find package "github.com/prometheus/common/version" in any of:
	/home/ubuntu/go/src/github.com/RobustPerception/nrpe_exporter/vendor/github.com/prometheus/common/version (vendor tree)
	/usr/local/go/src/github.com/prometheus/common/version (from $GOROOT)
	/home/ubuntu/go/src/github.com/prometheus/common/version (from $GOPATH)
```

I can fetch most of them with `go get`, but there's a problem:

```
$ go get
package github.com/cespare/xxhash/v2: cannot find package "github.com/cespare/xxhash/v2" in any of:
	/usr/local/go/src/github.com/cespare/xxhash/v2 (from $GOROOT)
	/home/ubuntu/go/src/github.com/cespare/xxhash/v2 (from $GOPATH)
$ go build .
../../prometheus/client_golang/prometheus/desc.go:22:2: cannot find package "github.com/cespare/xxhash/v2" in any of:
	/usr/local/go/src/github.com/cespare/xxhash/v2 (from $GOROOT)
	/home/ubuntu/go/src/github.com/cespare/xxhash/v2 (from $GOPATH)
```

Therefore, I have no idea how travis succeeds in building the code as it is today.

So the question is now: do you want to populate the `vendor/` directory with the missing dependencies, as they were around Oct 2017?  There seems little point having `vendor/` if it's incomplete.  But there also seems little point spending time on a legacy mechanism.

**Comment by candlerb** [comment]
> Therefore, I have no idea how travis succeeds in building the code as it is today.

Answer is: it doesn't - not under go 1.8 anyway, although it builds under go master.  I tested this as PR#11.

Are you happy to update dependencies with `go mod vendor` and lose the `vendor/vendor.json` file?  If so, I don't have to mess around with legacy tools like govendor.

**Comment by candlerb** [comment]
I've now made the change using the following approach:

```
go mod init github.com/RobustPerception/nrpe_exporter
go mod tidy
go mod vendor
# update the promlog usage to match updated promlog API
```

This has added all the missing vendored packages.  Note that there is now `modules.txt` instead of `vendor.json` in the `vendor/` directory.

I had to update the minimum go version to 1.9, because of an indirect dependency on "math/bits" from `cespare/xxhash/v2`.  The travis failure with 1.8 was:

```
$ travis_install_go_dependencies 1.8.x -v
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
```

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
